package com.anphat.list.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.combobox.FilteringMode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.cms.component.MappingCombobox;
import com.cms.utils.BundleUtils;
import com.cms.utils.MakeURL;


public class DepartmentSearchPanel extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private GridLayout gridLayout_1;
    @AutoGenerated
    private TextField txtDeptAddr;
    @AutoGenerated
    private Label lblDeptAddr;
    @AutoGenerated
    private TextField txtDeptEmail;
    @AutoGenerated
    private Label lblDeptEmail;
    @AutoGenerated
    private TextField txtDeptFax;
    @AutoGenerated
    private Label lblDeptFax;
    @AutoGenerated
    private TextField txtDeptPhone;
    @AutoGenerated
    private Label lblDeptPhone;
    @AutoGenerated
    private TextField txtDeptDesc;
    @AutoGenerated
    private Label lblDeptDesc;
    @AutoGenerated
    private ComboBox cboStatus;
    @AutoGenerated
    private Label lblStatus;
    @AutoGenerated
    private TextField txtContactPerson;
    @AutoGenerated
    private Label lblContactPerson;

    @AutoGenerated
    private Label lblDeptLevel;
    @AutoGenerated
    private TextField txtDeptName;
    @AutoGenerated
    private Label lblDeptName;
    @AutoGenerated
    private TextField txtDeptCode;
    @AutoGenerated
    private Label lblDeptCode;
    //f9
    MappingCombobox deptTopLevel;
    
    Button btnReset;
    //caption action tim kiem nang cao/tim kiem co ban
    private String lblSearchAdvance = BundleUtils.getString("search.advance");
    private String lblSearchBasic = BundleUtils.getString("search.basic");
    //layout chua linkaction
    private VerticalLayout verticalLayout;
    //nut xu li toogle
    private Button btnAdvanceSearch;
    //flag toogle
    boolean isAdvance = false;
    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public DepartmentSearchPanel() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // gridLayout_1
        gridLayout_1 = buildGridLayout_1();
        mainLayout.addComponent(gridLayout_1);

//            verticalLayout = new VerticalLayout();
//        verticalLayout.setImmediate(false);
//        verticalLayout.setWidth("100.0%");
//        verticalLayout.setHeight("100.0%");
//        verticalLayout.setMargin(false);
//        // gridLayout
//        verticalLayout.addComponent(gridLayout_1);
//        btnAdvanceSearch = new Button(lblSearchAdvance);
//        btnAdvanceSearch.setStyleName(Runo.BUTTON_LINK);
//        btnAdvanceSearch.setImmediate(true);
//        btnAdvanceSearch.addClickListener(new Button.ClickListener() {
//
//            @Override
//            public void buttonClick(Button.ClickEvent event) {
//                actionButton();
//            }
//        });
//        verticalLayout.addComponent(btnAdvanceSearch);
//        verticalLayout.setComponentAlignment(btnAdvanceSearch, Alignment.TOP_RIGHT);
//        mainLayout.addComponent(verticalLayout);
        return mainLayout;
    }

    @AutoGenerated
    private GridLayout buildGridLayout_1() {
        // common part: create layout
        gridLayout_1 = new GridLayout();
        gridLayout_1.setStyleName("custom-feildset");
        gridLayout_1.setCaption(MakeURL.makeURLForGrid(BundleUtils.getString("department.fieldset.title.deptInfo")));
        gridLayout_1.setCaptionAsHtml(true);
        gridLayout_1.setImmediate(false);
        gridLayout_1.setWidth("100.0%");
        gridLayout_1.setHeight("-1px");
        gridLayout_1.setMargin(true);
        gridLayout_1.setSpacing(true);
        gridLayout_1.setColumns(4);
        gridLayout_1.setRows(3);

        //mo rong khi chon tim kiem nang cao
        gridLayout_1.setRowExpandRatio(0, 1);
        gridLayout_1.setRowExpandRatio(1, 2);
        gridLayout_1.setRowExpandRatio(2, 3);
        gridLayout_1.setRowExpandRatio(3, 4);
        // lblDeptCode
        lblDeptCode = new Label();
        lblDeptCode.setImmediate(false);
        lblDeptCode.setWidth("100%");
        lblDeptCode.setHeight("-1px");
        lblDeptCode.setValue(BundleUtils.getString("lb.deptstaff.dept.code"));
        gridLayout_1.addComponent(lblDeptCode, 0, 0);

        // txtDeptCode
        txtDeptCode = new TextField();
        txtDeptCode.setImmediate(false);
        txtDeptCode.setWidth("100%");
        txtDeptCode.setHeight("-1px");
        txtDeptCode.setRequired(true);
        gridLayout_1.addComponent(txtDeptCode, 1, 0);

        // lblDeptName
        lblDeptName = new Label();
        lblDeptName.setImmediate(false);
        lblDeptName.setWidth("100%");
        lblDeptName.setHeight("-1px");
        lblDeptName.setValue(BundleUtils.getString("lb.deptstaff.dept.name"));
        gridLayout_1.addComponent(lblDeptName, 2, 0);

        // textField_2
        txtDeptName = new TextField();
        txtDeptName.setImmediate(false);
        txtDeptName.setWidth("100%");
        txtDeptName.setHeight("-1px");
        txtDeptName.setRequired(true);
        gridLayout_1.addComponent(txtDeptName, 3, 0);

        // lblDeptLevel
//        lblDeptLevel = new Label();
//        lblDeptLevel.setImmediate(false);
//        lblDeptLevel.setWidth("100%");
//        lblDeptLevel.setHeight("-1px");
//        lblDeptLevel.setValue(BundleUtils.getString("lb.deptstaff.dept.level"));
//        gridLayout_1.addComponent(lblDeptLevel, 0, 1);

//        deptTopLevel = new MappingCombobox(3, 1);
//        gridLayout_1.addComponent(deptTopLevel.getLayout(), 1, 1, 3, 1);
//        gridLayout_1.setComponentAlignment(deptTopLevel.getLayout(), Alignment.BOTTOM_LEFT);

        // lblStatus
        lblStatus = new Label();
        lblStatus.setImmediate(false);
        lblStatus.setWidth("100%");
        lblStatus.setHeight("-1px");
        lblStatus.setValue(BundleUtils.getString("lb.deptstaff.common.status"));
        gridLayout_1.addComponent(lblStatus, 2, 1);

        // cboStatus
        cboStatus = new ComboBox();
        cboStatus.setImmediate(true);
        cboStatus.setWidth("100%");
        cboStatus.setHeight("-1px");
        cboStatus.setTextInputAllowed(false);
        cboStatus.setFilteringMode(FilteringMode.OFF);
        cboStatus.setRequired(true);
        gridLayout_1.addComponent(cboStatus, 3, 1);

        // lblDeptEmail
        lblDeptEmail = new Label();
        lblDeptEmail.setImmediate(false);
        lblDeptEmail.setWidth("100%");
        lblDeptEmail.setHeight("-1px");
        lblDeptEmail.setValue(BundleUtils.getString("lb.deptstaff.common.email"));
        gridLayout_1.addComponent(lblDeptEmail, 0, 1);

        // txtDeptEmail
        txtDeptEmail = new TextField();
        txtDeptEmail.setImmediate(false);
        txtDeptEmail.setWidth("100%");
        txtDeptEmail.setHeight("-1px");
        gridLayout_1.addComponent(txtDeptEmail, 1, 1);

        // lblDeptAddr
        lblDeptAddr = new Label();
        lblDeptAddr.setImmediate(false);
        lblDeptAddr.setWidth("100%");
        lblDeptAddr.setHeight("-1px");
        lblDeptAddr.setValue(BundleUtils.getString("lb.deptstaff.dept.addr"));
        gridLayout_1.addComponent(lblDeptAddr, 0, 2);

        // txtDeptAddr
        txtDeptAddr = new TextField();
        txtDeptAddr.setImmediate(false);
        txtDeptAddr.setWidth("100%");
        txtDeptAddr.setHeight("-1px");
        txtDeptAddr.setRequired(true);
        gridLayout_1.addComponent(txtDeptAddr, 1, 2, 3, 2);

        // btnReset
//        GridLayout button = new GridLayout(1, 1);
//        button.setWidth("100%");
//        button.setHeight("-1px");
//        btnReset = new Button();
//        btnReset.setStyleName("v-button-link");
//        btnReset.setIcon(new ThemeResource("img/reset_icon.png"));
//        btnReset.setImmediate(true);
//        btnReset.setHeight("-1px");
//        btnReset.setDescription(Constants.BUTTON_REFRESH);
//        button.addComponent(btnReset);
//        button.setComponentAlignment(btnReset, Alignment.TOP_RIGHT);
//        gridLayout_1.addComponent(button, 3, 5);
        //
//        setVisibleComponents(isAdvance);
        return gridLayout_1;
    }

    public void actionButton() {
        if (isAdvance) {
            btnAdvanceSearch.setCaption(lblSearchAdvance);
            isAdvance = false;
        } else {
            btnAdvanceSearch.setCaption(lblSearchBasic);
            isAdvance = true;
        }
        txtDeptCode.focus();
        setVisibleComponents(isAdvance);
    }

    public void setVisibleComponents(boolean isVisible) {
//        lblDeptLevel.setVisible(isVisible);
        lblDeptAddr.setVisible(isVisible);
        txtDeptAddr.setVisible(isVisible);
//        deptTopLevel.setVisibleCombo(isVisible);
        if (!isAdvance) {
            txtDeptAddr.setValue("");
//            deptTopLevel.resetData();
        }
    }
    
    public TextField getTxtDeptAddr() {
        return txtDeptAddr;
    }

    public void setTxtDeptAddr(TextField txtDeptAddr) {
        this.txtDeptAddr = txtDeptAddr;
    }

    public TextField getTxtDeptEmail() {
        return txtDeptEmail;
    }

    public void setTxtDeptEmail(TextField txtDeptEmail) {
        this.txtDeptEmail = txtDeptEmail;
    }

    public TextField getTxtDeptFax() {
        return txtDeptFax;
    }

    public void setTxtDeptFax(TextField txtDeptFax) {
        this.txtDeptFax = txtDeptFax;
    }

    public TextField getTxtDeptPhone() {
        return txtDeptPhone;
    }

    public void setTxtDeptPhone(TextField txtDeptPhone) {
        this.txtDeptPhone = txtDeptPhone;
    }

    public TextField getTxtDeptDesc() {
        return txtDeptDesc;
    }

    public void setTxtDeptDesc(TextField txtDeptDesc) {
        this.txtDeptDesc = txtDeptDesc;
    }

    public ComboBox getCboStatus() {
        return cboStatus;
    }

    public void setCboStatus(ComboBox cboStatus) {
        this.cboStatus = cboStatus;
    }

    public TextField getTxtContactPerson() {
        return txtContactPerson;
    }

    public void setTxtContactPerson(TextField txtContactPerson) {
        this.txtContactPerson = txtContactPerson;
    }

    public TextField getTxtDeptName() {
        return txtDeptName;
    }

    public void setTxtDeptName(TextField txtDeptName) {
        this.txtDeptName = txtDeptName;
    }

    public TextField getTxtDeptCode() {
        return txtDeptCode;
    }

    public void setTxtDeptCode(TextField txtDeptCode) {
        this.txtDeptCode = txtDeptCode;
    }

//    public MappingCombobox getDeptTopLevel() {
//        return deptTopLevel;
//    }

//    public void setDeptTopLevel(MappingCombobox deptTopLevel) {
//        this.deptTopLevel = deptTopLevel;
//    }

    public Button getBtnReset() {
        return btnReset;
    }

    public void setBtnReset(Button btnReset) {
        this.btnReset = btnReset;
    }

}
