package com.cms.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Page;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Runo;

public class CommonTwoPanelUI extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    @AutoGenerated
    public VerticalLayout mainLayout;
    @AutoGenerated
    public HorizontalSplitPanel splitLayout;
    @AutoGenerated
    public Panel rightPanel;
    @AutoGenerated
    public VerticalLayout rightLayout;
    @AutoGenerated
    public Panel leftPanel;
    @AutoGenerated
    public VerticalLayout leftLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public CommonTwoPanelUI() {
        buildMainLayout();
        setCompositionRoot(mainLayout);
        //Style
//        Page.Styles styles = Page.getCurrent().getStyles();
//        styles.add("*{font-family: tahoma; font-size: 13px;}");
//        styles.add(".custom-feildset{border: 1px solid #ccc;}");
//        styles.add(".v-caption-custom-feildset{position: relative}");
//        styles.add(".v-caption-custom-feildset span{display: block; margin-top: -8px; position: absolute; z-index: 1000 !important; background: #fff;}");
//        styles.add(".v-textfield-dashing{background: #99EE6B;}");
//        styles.add(".boldLabel{font-weight:bold;}");
//        //Boi dam va can giua header
//        styles.add(".v-table-header-cell{text-align:center !important;font-weight:bold;}");
//        styles.add(".v-table-header-cell-asc{text-align:center !important;font-weight:bold;}");
//        styles.add(".v-table-header-cell-desc{text-align:center !important;font-weight:bold;}");
//        //Set bold caption Panel, button, grid fieldSet text
//        styles.add(".v-captiontext{font-weight:bold;} !important");
//        styles.add(".v-window-header{font-weight:bold !important;}");
//        styles.add(".v-panel-caption{font-weight:bold !important;}");
////        styles.add(".v-button-caption{font-weight:bold !important;}");
//        styles.add(".v-table-footer-container{font-weight:bold !important;}");        

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // splitLayout
        splitLayout = buildSplitLayout();
        mainLayout.addComponent(splitLayout);

        return mainLayout;
    }

    @AutoGenerated
    private HorizontalSplitPanel buildSplitLayout() {
        // common part: create layout
        splitLayout = new HorizontalSplitPanel();
        splitLayout.addStyleName(Runo.SPLITPANEL_SMALL);
        splitLayout.setImmediate(true);
        splitLayout.setWidth("100.0%");
        splitLayout.setHeight("100.0%");

        // leftPanel
        leftPanel = buildLeftPanel();
        splitLayout.addComponent(leftPanel);

        // rightPanel
        rightPanel = buildRightPanel();
        splitLayout.addComponent(rightPanel);

        return splitLayout;
    }

    @AutoGenerated
    private Panel buildLeftPanel() {
        // common part: create layout
        leftPanel = new Panel();
        leftPanel.setImmediate(true);
        leftPanel.setWidth("100.0%");
        leftPanel.setHeight("100%");

        // leftLayout
        leftLayout = new VerticalLayout();
        leftLayout.setImmediate(true);
        leftLayout.setWidth("100.0%");
        leftLayout.setHeight("-1px");
        leftLayout.setMargin(true);
        leftLayout.setSpacing(true);
        leftPanel.setContent(leftLayout);

        return leftPanel;
    }

    @AutoGenerated
    private Panel buildRightPanel() {
        // common part: create layout
        rightPanel = new Panel();
        rightPanel.setImmediate(true);
        rightPanel.setWidth("100%");
        rightPanel.setHeight("100%");

        // rightLayout
        rightLayout = new VerticalLayout();
        rightLayout.setImmediate(true);
        rightLayout.setWidth("100.0%");
        rightLayout.setHeight("-1px");
        rightLayout.setMargin(true);
        rightLayout.setSpacing(true);
        rightPanel.setContent(rightLayout);

        return rightPanel;
    }

}
