package com.cms.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.Runo;

public class CommonTable extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private VerticalLayout layoutTable;
    @AutoGenerated
    private CustomPageTable tblCommon; 

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     *
     * @param tblName
     */
    public CommonTable(String tblName, int pageLengh) {
        buildMainLayout(tblName, pageLengh);
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout(String tblName, int pageLengh) {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(true);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100%");

        // layoutTable
        layoutTable = buildLayoutTable(tblName, pageLengh);
        mainLayout.addComponent(layoutTable);

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildLayoutTable(String tblName, int pageLengh) {
        // common part: create layout
        layoutTable = new VerticalLayout();
        layoutTable.setStyleName("custom-feildset");
        layoutTable.setCaption(tblName);
        layoutTable.setImmediate(true);
        layoutTable.setWidth("100.0%");
        layoutTable.setHeight("100%");
        layoutTable.setMargin(true);

        // tblCommon
        tblCommon = new CustomPageTable();
        tblCommon.setImmediate(true);
        tblCommon.setSelectable(true);
        tblCommon.setStyleName(Runo.TABLE_SMALL);
        tblCommon.setWidth("100.0%");
        tblCommon.setHeight("-1px");
        tblCommon.setPageLength(pageLengh);
        tblCommon.setFooterVisible(true);
        layoutTable.addComponent(tblCommon);
        layoutTable.addComponent(tblCommon.createControls(String.valueOf(tblCommon.getPageLength())));
        return layoutTable;
    }

    public CustomPageTable getTblCommon() {
        return tblCommon;
    }

    public void setTblCommon(CustomPageTable tblCommon) {
        this.tblCommon = tblCommon;
    }

    public VerticalLayout getLayoutTable() {
        return layoutTable;
    }

    public void setLayoutTable(VerticalLayout layoutTable) {
        this.layoutTable = layoutTable;
    }

}
