package com.cms.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class CommonOnePanelUI extends CustomComponent {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    @AutoGenerated
    public VerticalLayout mainLayout;
    @AutoGenerated
    public Panel panelMain;
    @AutoGenerated
    public VerticalLayout layoutMain;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public CommonOnePanelUI() {        
//        Page.Styles styles = Page.getCurrent().getStyles();
//        styles.add("*{font-family: tahoma; font-size: 13px;}");
//        styles.add(".custom-feildset{border: 1px solid #ccc;}");
//        styles.add(".v-caption-custom-feildset{position: relative}");
//        styles.add(".v-caption-custom-feildset span{display: block; margin-top: -8px; position: absolute; z-index: 1000 !important; background: #fff;}");
//        styles.add(".v-textfield-dashing{background: #99EE6B;}");
//        styles.add(".boldLabel{font-weight:bold;}");
        //Boi dam va can giua header
//        styles.add(".v-table-header-cell{text-align:center !important;font-weight:bold;}");
//        styles.add(".v-table-header-cell-asc{text-align:center !important;font-weight:bold;}");
//        styles.add(".v-table-header-cell-desc{text-align:center !important;font-weight:bold;}");
//        //Set bold caption Panel, button, grid fieldSet text
//        styles.add(".v-captiontext{font-weight:bold;} !important");
//        styles.add(".v-window-header{font-weight:bold !important;}");
//        styles.add(".v-panel-caption{font-weight:bold !important;}");
////        styles.add(".v-button-caption{font-weight:bold !important;}");
//        styles.add(".v-table-footer-container{font-weight:bold !important;}");

        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100%");

        // panelMain
        panelMain = buildPanelMain();
        mainLayout.addComponent(panelMain);

        return mainLayout;
    }

    @AutoGenerated
    private Panel buildPanelMain() {
        // common part: create layout
        panelMain = new Panel();
        panelMain.setImmediate(false);
        
        panelMain.setWidth("100.0%");
        panelMain.setHeight("100%");

        // layoutMain
        layoutMain = new VerticalLayout();
        layoutMain.setImmediate(false);
        layoutMain.setWidth("100.0%");
        layoutMain.setHeight("-1px");
        layoutMain.setMargin(true);
        layoutMain.setSpacing(true);
        panelMain.setContent(layoutMain);
        return panelMain;
    }

}
