package com.cms.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Page;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.cms.utils.DataUtil;
//import com.viettel.logistics.utils.DataUtil;

public class CommonDialog extends Window {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    @AutoGenerated
    protected VerticalLayout mainLayout;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public CommonDialog() {
        buildMainLayout();
        setContent(mainLayout);
        setModal(true);
        //Style
        Page.Styles styles = Page.getCurrent().getStyles();
        styles.add("*{font-family: tahoma; font-size: 13px;}");
        styles.add(".custom-feildset{border: 1px solid #ccc;}");
        styles.add(".v-caption-custom-feildset{position: relative}");
        styles.add(".v-caption-custom-feildset span{display: block; margin-top: -8px; position: absolute; z-index: 1000 !important; background: #fff;}");
        styles.add(".v-textfield-dashing{background: #99EE6B;}");
        styles.add(".boldLabel{font-weight:bold;}");
        //Boi dam va can giua header
        styles.add(".v-table-header-cell{text-align:center !important;font-weight:bold;}");
        styles.add(".v-table-header-cell-asc{text-align:center !important;font-weight:bold;}");
        styles.add(".v-table-header-cell-desc{text-align:center !important;font-weight:bold;}");
        //Set bold caption Panel, button, grid fieldSet text
        styles.add(".v-captiontext{font-weight:bold;} !important");
        styles.add(".v-window-header{font-weight:bold !important;}");
        styles.add(".v-panel-caption{font-weight:bold !important;}");
//        styles.add(".v-button-caption{font-weight:bold !important;}");
        styles.add(".v-table-footer-container{font-weight:bold !important;}");

    }

    protected void setInfo(String width, String height, String caption) {
        setWidth(width);
        setHeight(height);
        setCaption(caption);
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(true);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("-1px");
        mainLayout.setMargin(true);
        DataUtil.reloadWindow(this);
        // top-level component properties
        setWidth("100.0%");
        setHeight("-1px");
        return mainLayout;
    }

    public VerticalLayout getMainLayout() {
        return mainLayout;
    }

    public void setMainLayout(VerticalLayout mainLayout) {
        this.mainLayout = mainLayout;
    }
}
